steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-west4-docker.pkg.dev/springboothello-433901/spring-boot-helloworld", "--build-arg=JAR_FILE=target/helloworld-0.0.1-SNAPSHOT.jar", "."]
images: ["us-west4-docker.pkg.dev/springboothello-433901/spring-boot-helloworld"]
options:
  logging: CLOUD_LOGGING_ONLY