spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY_CLOAK_ISSUER_URI}
          jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/${JWK_SET_URI}
  application:
    name: pets application
  datasource:
    url: jdbc:postgresql://localhost:5543/pet_shop
    username: ${PET_DB_USER}
    password: ${PET_DB_PSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true


server:
  port: 8785