spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY_CLOAK_ISSUER_URI}
          jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/${JWK_SET_URI}
  application:
    name: pet-backend
  datasource:
    url: ${PET_BACK_END_DB_URL}
    username: ${PET_DB_USER}
    password: ${PET_DB_PSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${PET_BACK_END_DB_URL}
    user: ${PET_DB_USER}
    password: ${PET_DB_PSWD}
    locations: classpath:db/migration



  profiles:
    active: dev

  cloud:
    config:
      label: latest

  config:
    import: configserver:http://localhost:8888
server:
  port: 8785