spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEY_CLOAK_ISSUER_URI}
          jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/${JWK_SET_URI}
  application:
    name: pet-backend
  datasource:
    url: ${DB_URL}/pet_shop
    username: ${PET_DB_USER}
    password: ${PET_DB_PSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${DB_URL}/pet_shop
    user: ${PET_DB_USER}
    password: ${PET_DB_PSWD}
    locations: classpath:db/migration



  profiles:
    active: dev

  cloud:
    config:
      label: latest

  config:
    import: configserver:${CONFIG_SERVER_URL}
server:
  port: 8785