spring:
  application:
    name: pets application
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_shop
    username: postgres
    password: d3vp3t4pp
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true


server:
  port: 8785