spring:
  application:
    name: pets application
  datasource:
    url: jdbc:postgresql://localhost:5543/pet_shop
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

  