INSERT INTO pets_tb (pet_name, pet_description) VALUES
('Spot', 'Naughty Brown Chihuahua'),
('Jack', 'Green African Mongoose'),
('Rango', 'A bright colored Gecko'),
('Bella', 'Playful Golden Retriever'),
('Luna', 'Curious Siamese Cat'),
('Max', 'Energetic Border Collie'),
('Charlie', 'Loyal German Shepherd'),
('Milo', 'Charming Persian Cat'),
('Lucy', 'Friendly Beagle'),
('Daisy', 'Sweet Shih Tzu'),
('Rocky', 'Brave Rottweiler'),
('Coco', 'Cute Yorkshire Terrier'),
('Ziggy', 'Adventurous Ferret'),
('Oliver', 'Gentle Maine Coon'),
('Chloe', 'Sassy Sphynx Cat'),
('Buddy', 'Loving Labrador'),
('Sophie', 'Elegant Great Dane'),
('Teddy', 'Fluffy Bichon Frise'),
('Gizmo', 'Playful Hamster'),
('Nala', 'Intelligent Akita'),
('Simba', 'Majestic Bengal Cat'),
('Fido', 'Cheerful Cocker Spaniel'),
('Duke', 'Strong Boxer'),
('Maggie', 'Affectionate Australian Shepherd'),
('Toby', 'Friendly Dachshund'),
('Penny', 'Charming French Bulldog'),
('Rusty', 'Adventurous Jack Russell Terrier'),
('Willow', 'Gentle Greyhound'),
('Pepper', 'Spunky Poodle'),
('Koda', 'Loyal Siberian Husky'),
('Toby', 'Curious Chihuahua'),
('Lola', 'Graceful Scottish Fold'),
('Bailey', 'Friendly Shiba Inu'),
('Finn', 'Playful Golden Doodle'),
('Misty', 'Sweet Cocker Spaniel'),
('Rex', 'Eager Doberman'),
('Zara', 'Elegant Abyssinian Cat'),
('Buster', 'Brave Pembroke Corgi'),
('Stella', 'Adorable Cavalier King Charles Spaniel'),
('Oscar', 'Charming Sphynx Cat'),
('Ruby', 'Loving Labrador Retriever'),
('Jasper', 'Intelligent Border Terrier'),
('Sasha', 'Adorable Pug'),
('Nina', 'Playful Bearded Dragon'),
('Mochi', 'Cute Chinchilla'),
('Whiskers', 'Curious Abyssinian'),
('Cinnamon', 'Fluffy Himalayan Cat'),
('Marley', 'Friendly Boston Terrier'),
('Zoe', 'Spirited Dachshund'),
('Kiki', 'Playful Ferret'),
('Archie', 'Gentle Boxer'),
('Piper', 'Sassy French Bulldog'),
('Harley', 'Adventurous Rottweiler'),
('Roxy', 'Loyal Siberian Husky'),
('Theo', 'Charming Maltese'),
('Luna', 'Elegant Russian Blue'),
('Milo', 'Friendly Tabby Cat'),
('Coco', 'Cute Shih Tzu'),
('Juno', 'Playful Pomeranian'),
('Dexter', 'Adventurous Pit Bull'),
('Chester', 'Loving Great Dane'),
('Angel', 'Graceful Persian Cat'),
('Ginger', 'Spunky Bearded Dragon'),
('Pumpkin', 'Friendly Ferret'),
('Tango', 'Energetic Chihuahua'),
('Sable', 'Charming Ragdoll Cat'),
('Nugget', 'Cheerful Boston Terrier'),
('Biscuit', 'Sweet Pekingese'),
('Scout', 'Brave German Shepherd'),
('Cuddles', 'Affectionate Pomeranian'),
('Poppy', 'Playful Toy Poodle'),
('Bambi', 'Gentle Bichon Frise'),
('Boomer', 'Loyal Labrador'),
('Pita', 'Curious Corn Snake'),
('Ziggy', 'Spunky Parakeet'),
('Pebbles', 'Adventurous Hamster'),
('Coco', 'Friendly Cockatiel'),
('Snowball', 'Fluffy Angora Rabbit'),
('Dobby', 'Loving Shih Tzu'),
('Mochi', 'Cute Cavy'),
('Hazel', 'Elegant Abyssinian'),
('Chester', 'Charming Scottish Fold'),
('Buster', 'Energetic Beagle'),
('Lucky', 'Playful Dalmatian'),
('Maisie', 'Affectionate Golden Retriever'),
('Ollie', 'Spirited Cocker Spaniel'),
('Gizmo', 'Charming Ferret'),
('Sunny', 'Friendly Parrot'),
('Basil', 'Adventurous Gecko'),
('Candy', 'Sweet Pomeranian'),
('Frosty', 'Gentle Husky'),
('Willow', 'Elegant Maine Coon'),
('Smokey', 'Curious Russian Blue'),
('Misty', 'Sassy Bengal Cat'),
('Nemo', 'Playful Betta Fish'),
('Orion', 'Loyal Boxer'),
('Clover', 'Gentle Labrador'),
('Misty', 'Sweet Cavalier King Charles Spaniel'),
('Mia', 'Loving Great Dane'),
('Mocha', 'Charming Pekingese'),
('Leo', 'Brave Rottweiler'),
('Zara', 'Adventurous Beagle'),
('Pumpkin', 'Fluffy Bichon Frise'),
('Sprout', 'Curious African Grey Parrot'),
('Koda', 'Loving Shiba Inu'),
('Coco', 'Sweet Yorkshire Terrier'),
('Jasper', 'Playful Cocker Spaniel'),
('Benny', 'Gentle Golden Retriever'),
('Toby', 'Friendly Pug'),
('Ellie', 'Curious Maine Coon'),
('Gus', 'Adventurous Pembroke Corgi'),
('Rocky', 'Spirited Dalmatian'),
('Peanut', 'Charming Pekingese'),
('Biscuit', 'Loving Beagle'),
('Roo', 'Energetic Chihuahua'),
('Gizmo', 'Adventurous Hamster'),
('Harper', 'Sweet Cavalier King Charles Spaniel'),
('Nova', 'Friendly Labrador'),
('Nina', 'Curious Siamese Cat'),
('Fiona', 'Gentle Great Dane'),
('Ziggy', 'Spunky Rottweiler'),
('Muffin', 'Charming Shih Tzu'),
('Mocha', 'Playful Pomeranian'),
('Nugget', 'Energetic Ferret'),
('Sophie', 'Gentle Maine Coon'),
('Riley', 'Adventurous Boxer'),
('Milo', 'Cheerful Dachshund'),
('Coco', 'Friendly Yorkshire Terrier'),
('Willow', 'Curious Abyssinian'),
('Oreo', 'Spunky Pug'),
('Lucky', 'Brave German Shepherd'),
('Hazel', 'Loving Ragdoll Cat'),
('Buster', 'Gentle Bulldog'),
('Sunny', 'Playful Cocker Spaniel'),
('Chester', 'Adventurous Beagle'),
('Roxy', 'Curious Sphynx Cat'),
('Daisy', 'Charming Shih Tzu'),
('Snowy', 'Fluffy Angora Rabbit'),
('Ranger', 'Loyal Siberian Husky'),
('Nina', 'Sweet Pomeranian'),
('Mia', 'Elegant Maine Coon'),
('Teddy', 'Energetic Golden Retriever'),
('Bella', 'Friendly French Bulldog'),
('Gizmo', 'Playful Ferret'),
('Nugget', 'Adventurous Cavy'),
('Leo', 'Cheerful Rottweiler'),
('Bobby', 'Gentle Labrador'),
('Coco', 'Sassy Boxer'),
('Rusty', 'Curious Dalmatian'),
('Butters', 'Charming Beagle'),
('Misty', 'Adventurous Cocker Spaniel'),
('Pip', 'Gentle Yorkshire Terrier'),
('Mochi', 'Playful Pekingese'),
('Zara', 'Friendly Great Dane'),
('Chester', 'Curious Abyssinian'),
('Fido', 'Brave German Shepherd'),
('Nova', 'Loving Shih Tzu'),
('Benny', 'Energetic Cocker Spaniel'),
('Ziggy', 'Charming Rottweiler'),
('Scout', 'Playful Beagle'),
('Sasha', 'Sweet Labrador'),
('Buddy', 'Adventurous Boxer'),
('Pepper', 'Loyal Shiba Inu'),
('Rocky', 'Curious Golden Retriever'),
('Nala', 'Charming Sphynx Cat'),
('Misty', 'Gentle Ragdoll'),
('Rex', 'Spunky Pug'),
('Cinnamon', 'Playful Ferret'),
('Piper', 'Friendly Yorkshire Terrier'),
('Luna', 'Sweet Cavalier King Charles Spaniel'),
('Oliver', 'Cuddly Maine Coon'),
('Buster', 'Brave Beagle'),
('Kiki', 'Charming Shih Tzu'),
('Gizmo', 'Curious Ferret'),
('Tango', 'Adventurous Pomeranian'),
('Rusty', 'Playful Boxer'),
('Chloe', 'Loving Golden Retriever'),
('Milo', 'Gentle Cocker Spaniel'),
('Nina', 'Friendly Ragdoll Cat'),
('Coco', 'Sassy Siberian Husky'),
('Ziggy', 'Curious Chihuahua'),
('Ruby', 'Adventurous Pug'),
('Daisy', 'Sweet Shih Tzu'),
('Biscuit', 'Gentle Beagle'),
('Misty', 'Loving Golden Retriever'),
('Pebbles', 'Charming Cavy'),
('Lucky', 'Playful Ferret'),
('Koda', 'Loyal Siberian Husky'),
('Toby', 'Curious Chihuahua'),
('Ginger', 'Sweet Ragdoll Cat'),
('Rocky', 'Brave Boxer'),
('Nala', 'Friendly Dalmatian'),
('Bella', 'Charming Pekingese'),
('Finn', 'Energetic Golden Retriever'),
('Sasha', 'Gentle Shiba Inu'),
('Mia', 'Loving Maine Coon'),
('Coco', 'Curious Beagle'),
('Ollie', 'Playful Cocker Spaniel'),
('Zara', 'Friendly Rottweiler'),
('Mochi', 'Sweet Pomeranian'),
('Theo', 'Charming Boxer'),
('Misty', 'Gentle Cavalier King Charles Spaniel'),
('Rex', 'Adventurous Labrador'),
('Jasper', 'Loyal Shih Tzu'),
('Penny', 'Curious Pug'),
('Milo', 'Playful Ferret'),
('Cuddles', 'Sweet Yorkshire Terrier'),
('Gizmo', 'Charming Cocker Spaniel'),
('Luna', 'Friendly Golden Retriever'),
('Scout', 'Gentle Boxer'),
('Chester', 'Playful Beagle'),
('Buster', 'Brave Rottweiler'),
('Lucky', 'Adventurous Shiba Inu'),
('Nina', 'Curious Ragdoll Cat'),
('Daisy', 'Loving Golden Retriever'),
('Piper', 'Sassy Cocker Spaniel'),
('Nugget', 'Friendly Ferret'),
('Bella', 'Charming Labrador'),
('Ziggy', 'Playful Beagle'),
('Roxy', 'Gentle Siberian Husky'),
('Misty', 'Loving Pekingese'),
('Fido', 'Curious Shih Tzu'),
('Milo', 'Friendly Golden Retriever'),
('Pumpkin', 'Adventurous Boxer'),
('Kiki', 'Sweet Yorkshire Terrier'),
('Nala', 'Gentle Pomeranian'),
('Bob', 'Spunky Dalmatian'),
('Luna', 'Loving Siberian Husky'),
('Chester', 'Charming Cocker Spaniel'),
('Misty', 'Gentle Ragdoll Cat'),
('Finn', 'Curious Golden Retriever'),
('Coco', 'Playful Cavy'),
('Biscuit', 'Friendly Ferret'),
('Misty', 'Loving Shih Tzu'),
('Zara', 'Adventurous Pug'),
('Fido', 'Energetic Boxer'),
('Penny', 'Sweet Labrador'),
('Lucky', 'Curious Dachshund'),
('Bella', 'Charming Beagle'),
('Milo', 'Gentle Golden Retriever'),
('Nina', 'Playful Ferret'),
('Koda', 'Loving Siberian Husky'),
('Daisy', 'Friendly Pomeranian'),
('Coco', 'Sassy Shih Tzu'),
('Rex', 'Brave Boxer'),
('Gizmo', 'Curious Cavy'),
('Rocky', 'Adventurous Beagle'),
('Lucky', 'Gentle Rottweiler'),
('Misty', 'Friendly Cocker Spaniel'),
('Nugget', 'Sweet Pomeranian'),
('Biscuit', 'Playful Ferret'),
('Milo', 'Charming Shih Tzu'),
('Piper', 'Gentle Labrador'),
('Zara', 'Curious Pug'),
('Scout', 'Loving Rottweiler'),
('Daisy', 'Sweet Golden Retriever'),
('Coco', 'Friendly Cocker Spaniel'),
('Bella', 'Charming Shih Tzu'),
('Lucky', 'Energetic Ferret'),
('Misty', 'Gentle Pomeranian'),
('Theo', 'Curious Beagle'),
('Fido', 'Adventurous Boxer'),
('Nina', 'Friendly Ragdoll Cat'),
('Rusty', 'Cuddly Shiba Inu'),
('Oliver', 'Sweet Chocolate Lab'),
('Harper', 'Friendly Pekingese'),
('Milo', 'Charming Cocker Spaniel'),
('Jasper', 'Loyal Beagle'),
('Coco', 'Sassy Golden Retriever'),
('Daisy', 'Gentle Boxer'),
('Lucky', 'Curious Pomeranian'),
('Misty', 'Loving Shih Tzu'),
('Nugget', 'Playful Ferret'),
('Scout', 'Friendly Rottweiler'),
('Penny', 'Charming Cocker Spaniel'),
('Gizmo', 'Gentle Golden Retriever'),
('Bella', 'Sweet Pekingese'),
('Milo', 'Adventurous Boxer'),
('Ziggy', 'Curious Dalmatian'),
('Nina', 'Friendly Ragdoll Cat'),
('Coco', 'Gentle Shih Tzu'),
('Finn', 'Playful Labrador'),
('Lucky', 'Curious Cocker Spaniel'),
('Rocky', 'Loving Pomeranian'),
('Misty', 'Friendly Pekingese'),
('Daisy', 'Sweet Cocker Spaniel'),
('Jasper', 'Charming Golden Retriever'),
('Zara', 'Gentle Boxer'),
('Nugget', 'Adventurous Ferret'),
('Coco', 'Playful Shih Tzu'),
('Milo', 'Friendly Rottweiler'),
('Biscuit', 'Charming Beagle'),
('Lucky', 'Curious Pomeranian'),
('Misty', 'Sweet Cocker Spaniel'),
('Daisy', 'Loving Golden Retriever'),
('Finn', 'Gentle Cocker Spaniel'),
('Penny', 'Adventurous Pug'),
('Rocky', 'Curious Shiba Inu'),
('Coco', 'Playful Yorkshire Terrier'),
('Bella', 'Friendly Boxer'),
('Nina', 'Charming Ragdoll Cat'),
('Scout', 'Gentle Beagle'),
('Jasper', 'Loving Pomeranian'),
('Misty', 'Curious Shih Tzu'),
('Daisy', 'Friendly Golden Retriever'),
('Lucky', 'Playful Ferret'),
('Milo', 'Sweet Cocker Spaniel'),
('Nugget', 'Charming Pekingese'),
('Coco', 'Gentle Boxer'),
('Finn', 'Adventurous Rottweiler'),
('Rex', 'Curious Beagle'),
('Jasper', 'Loving Shih Tzu'),
('Misty', 'Friendly Labrador'),
('Zara', 'Sweet Cocker Spaniel'),
('Lucky', 'Playful Ferret'),
('Bella', 'Charming Pomeranian'),
('Pepper', 'Adventurous Boxer'),
('Nina', 'Gentle Shiba Inu'),
('Coco', 'Friendly Pekingese'),
('Finn', 'Curious Golden Retriever'),
('Misty', 'Loving Cocker Spaniel'),
('Penny', 'Playful Rottweiler'),
('Rocky', 'Charming Beagle'),
('Daisy', 'Gentle Labrador'),
('Lucky', 'Sweet Shih Tzu'),
('Coco', 'Friendly Ragdoll Cat'),
('Misty', 'Curious Pomeranian'),
('Gizmo', 'Charming Ferret'),
('Milo', 'Playful Beagle'),
('Nina', 'Gentle Shiba Inu'),
('Scout', 'Loving Golden Retriever'),
('Zara', 'Curious Cocker Spaniel'),
('Pepper', 'Sweet Pekingese'),
('Biscuit', 'Adventurous Boxer'),
('Lucky', 'Friendly Ragdoll Cat'),
('Daisy', 'Charming Pomeranian'),
('Misty', 'Gentle Golden Retriever'),
('Finn', 'Curious Cocker Spaniel'),
('Nugget', 'Playful Ferret'),
('Misty', 'Loving Shih Tzu'),
('Zara', 'Sweet Cocker Spaniel'),
('Coco', 'Adventurous Beagle'),
('Rocky', 'Friendly Rottweiler'),
('Nina', 'Charming Golden Retriever'),
('Milo', 'Gentle Pekingese'),
('Lucky', 'Curious Shih Tzu'),
('Pepper', 'Adventurous Boxer'),
('Bella', 'Friendly Ragdoll Cat'),
('Scout', 'Sweet Pomeranian'),
('Daisy', 'Loving Golden Retriever'),
('Finn', 'Gentle Beagle'),
('Coco', 'Playful Cocker Spaniel'),
('Jasper', 'Charming Shih Tzu'),
('Misty', 'Curious Ferret'),
('Penny', 'Friendly Rottweiler'),
('Nugget', 'Adventurous Boxer'),
('Rocky', 'Sweet Pekingese'),
('Lucky', 'Curious Golden Retriever'),
('Misty', 'Charming Cocker Spaniel'),
('Daisy', 'Gentle Beagle'),
('Coco', 'Playful Pomeranian'),
('Finn', 'Friendly Shiba Inu'),
('Nina', 'Charming Golden Retriever'),
('Biscuit', 'Adventurous Ferret'),
('Lucky', 'Sweet Labrador'),
('Misty', 'Gentle Cocker Spaniel'),
('Penny', 'Charming Rottweiler'),
('Milo', 'Friendly Pekingese'),
('Rocky', 'Curious Beagle'),
('Daisy', 'Adventurous Cocker Spaniel'),
('Zara', 'Sweet Shih Tzu'),
('Coco', 'Loving Ferret'),
('Scout', 'Charming Boxer'),
('Finn', 'Gentle Golden Retriever'),
('Nina', 'Friendly Yorkshire Terrier'),
('Penny', 'Playful Pomeranian'),
('Misty', 'Adventurous Cocker Spaniel'),
('Daisy', 'Charming Rottweiler'),
('Lucky', 'Sweet Beagle'),
('Milo', 'Curious Shih Tzu'),
('Coco', 'Friendly Pekingese'),
('Finn', 'Playful Ferret'),
('Penny', 'Adventurous Labrador'),
('Daisy', 'Charming Boxer'),
('Misty', 'Gentle Shih Tzu'),
('Lucky', 'Curziman');